version: '3'

services:
  # MongoDB database
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
   # volumes:
    # - db:/data/db 
    ports:
     - "27017:27017"
    command: mongod --bind_ip 0.0.0.0


# node app
  app:
    build: .
    ports:
     - "80:3000"
    environment:
     - DB_HOST=mongodb://mongo_db:27017/posts
    depends_on:
     - mongo_db
